apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigipreport.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "bigipreport.labels" . | nindent 4 }}
data:
  bigipreportconfig.xml: |
    {{- .Files.Get "bigipreportconfig.xml" | nindent 4 }}
