apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bigipreport.pvcName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "bigipreport.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size }}
  {{- with .Values.persistentStorage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
