apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bigipreport-pvc
  namespace: "{{ .Release.Namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
