apiVersion: v1
kind: Service
metadata:
  name: bigipreport
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: bigipreport
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
